<a href="https://colab.research.google.com/github/Dennis-Rotich/Frozen_lake-OpenAI-gymnasium/blob/main/Frozen_Lake_Reinforcement_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import gymnasium as gym
import numpy as np
import time

env = gym.make('FrozenLake-v1')
STATES = env.observation_space.n
ACTIONS = env.action_space.n

Q = np.zeros((STATES, ACTIONS))

EPISODES = 1500
MAX_STEPS = 100

LEARNING_RATE = 0.81
GAMMA = 0.96

RENDER = False

epsilon = 0.9

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [11]:
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
rewards = []
for episode in range(EPISODES):

  state, info = env.reset()
  for _ in range(MAX_STEPS):

    if RENDER:
      env.render()

    if np.random.uniform(0, 1) < epsilon:
      action = env.action_space.sample()
    else:
      action = np.argmax(Q[state, :])

    next_state, reward, terminated, truncated, info = env.step(action)

    Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA * np.max(Q[next_state, :]) - Q[state, action])

    state = next_state

    done = terminated or truncated
    if done:
      rewards.append(reward)
      epsilon -= 0.001
      break

print(Q)
print(f"Average reward: {sum(rewards)/len(rewards)}:")

[[3.03192315e-01 1.19776477e-02 1.72312354e-02 1.72725713e-02]
 [4.86659539e-03 2.07801118e-03 4.39456340e-03 1.40897533e-01]
 [3.09303485e-03 3.56980610e-03 1.69208416e-03 1.68351989e-01]
 [4.89992888e-03 2.74888423e-03 4.81229615e-03 9.40945721e-02]
 [5.26576520e-01 8.81199582e-03 1.03549389e-02 9.74593129e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.81695542e-05 3.72985030e-05 3.62173591e-02 3.03431809e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.17265874e-03 1.33690115e-02 1.42884804e-02 5.80370589e-01]
 [8.11473632e-03 6.84410157e-01 5.15924744e-03 5.86834542e-03]
 [3.00827987e-01 4.41473339e-04 1.46445966e-03 7.62681914e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.86720477e-02 4.21948596e-02 3.06340693e-01 2.41111378e-02]
 [1.51422880e-01 8.03326400e-01 1.53880941e-01 1.90992354e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000